# Generated by Django 5.2.3 on 2025-06-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('category', models.CharField(max_length=50, verbose_name='网站分类')),
                ('method', models.TextField(verbose_name='爬取方法')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
